/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_.buku;

import CONTROLLER_.C_Buku;
import MODEL_.M_Buku;
import java.awt.event.KeyEvent;
import java.text.Normalizer;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author frans
 */
public class editBuku extends javax.swing.JFrame {

    /**
     * Creates new form editBuku
     */
//    public editBuku() {
//        initComponents();
//        this.setLocationRelativeTo(null);
//    }
    private String bookISBN;

    public editBuku(String isbn_buku) {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            System.out.println("PROCESSING...");
            M_Buku dataBuku = new C_Buku().getDetailBuku(isbn_buku);

            jLabel_isbn.setText("ISBN : " + dataBuku.getBook_isbn());
            textF_judul.setText(dataBuku.getBook_title());
            textF_author.setText(dataBuku.getBook_author());
            textF_publisher.setText(dataBuku.getBook_pub());
            textF_year.setText(Integer.toString(dataBuku.getYear_of_pub()));
            textF_url.setText(dataBuku.getBook_img_url());

            bookISBN = dataBuku.getBook_isbn();
            System.out.println("IDLE");
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "ERR..  CONNECTION FAILED!\n" + e.getMessage());
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_isbn = new javax.swing.JLabel();
        label_judul = new javax.swing.JLabel();
        textF_judul = new javax.swing.JTextField();
        textF_author = new javax.swing.JTextField();
        label_judul1 = new javax.swing.JLabel();
        textF_publisher = new javax.swing.JTextField();
        label_judul2 = new javax.swing.JLabel();
        textF_year = new javax.swing.JTextField();
        label_judul3 = new javax.swing.JLabel();
        textF_url = new javax.swing.JTextField();
        label_judul4 = new javax.swing.JLabel();
        btn_simpanPerubahanEditBuku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Edit Buku");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_isbn.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel_isbn.setText("#ISBN");

        label_judul.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_judul.setText("Judul");

        textF_judul.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textF_judul.setText("#judul");

        textF_author.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textF_author.setText("#author");

        label_judul1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_judul1.setText("Author");

        textF_publisher.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textF_publisher.setText("#publisher");

        label_judul2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_judul2.setText("Publiser");

        textF_year.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textF_year.setText("#year");

        label_judul3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_judul3.setText("Year");

        textF_url.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textF_url.setText("#URL");

        label_judul4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_judul4.setText("Img URL");

        btn_simpanPerubahanEditBuku.setText("Simpan");
        btn_simpanPerubahanEditBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanPerubahanEditBukuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textF_judul))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textF_author, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textF_publisher))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textF_year))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_judul4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textF_url)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_isbn)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_simpanPerubahanEditBuku)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_isbn)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textF_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textF_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textF_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textF_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_judul4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textF_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_simpanPerubahanEditBuku)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanPerubahanEditBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanPerubahanEditBukuMouseClicked
        String regex_ = "[0-9]+";

        if (textF_year.getText().matches(regex_)) {
            if (textF_author.getText().equals("") || textF_judul.getText().equals("") || textF_publisher.getText().equals("") || textF_year.getText().equals("") || textF_url.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Input Tidak Valid", "ERROR", JOptionPane.WARNING_MESSAGE);
            } else {
                M_Buku dataBuku = new M_Buku();
                dataBuku.setBook_isbn(bookISBN);
                dataBuku.setBook_author(removeSpcialChar(textF_author.getText()));
                dataBuku.setBook_title(removeSpcialChar(textF_judul.getText()));
                dataBuku.setYear_of_pub(Integer.parseInt(textF_year.getText()));
                dataBuku.setBook_img_url(textF_url.getText());
                dataBuku.setBook_pub(removeSpcialChar(textF_publisher.getText()));
                System.out.println("PROCESSING...");
                try {
                    new C_Buku().save_EditBuku(dataBuku);

                    this.dispose();
                    System.out.println("IDLE");
                    JOptionPane.showMessageDialog(null, "Berhasil Simpan");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e, "ERROR", JOptionPane.WARNING_MESSAGE);
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Input Tidak Valid", "ERROR", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btn_simpanPerubahanEditBukuMouseClicked

    String removeSpcialChar(String str) {
        String normalized = Normalizer.normalize(str, Normalizer.Form.NFD);
        String result = normalized.replaceAll("[^A-Za-z0-9]", " ");
        return result;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpanPerubahanEditBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_isbn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_judul;
    private javax.swing.JLabel label_judul1;
    private javax.swing.JLabel label_judul2;
    private javax.swing.JLabel label_judul3;
    private javax.swing.JLabel label_judul4;
    private javax.swing.JTextField textF_author;
    private javax.swing.JTextField textF_judul;
    private javax.swing.JTextField textF_publisher;
    private javax.swing.JTextField textF_url;
    private javax.swing.JTextField textF_year;
    // End of variables declaration//GEN-END:variables
}
